# Copyright 2026 Ori Nexus Systems LTD
# SPDX-License-Identifier: Apache-2.0

"""Transactional persistence operations for authors and skill publications."""

from __future__ import annotations

from datetime import datetime
from typing import NoReturn

from sqlalchemy import func, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from hub.core.models import SkillStatus
from hub.db._models import (
    ArtifactModel,
    AuthorCredentialModel,
    AuthorModel,
    SkillTransitionAuditModel,
    SkillVersionModel,
    new_record_id,
)
from hub.db.errors import (
    InvalidStateTransitionError,
    PersistenceConflictError,
    RecordNotFoundError,
)
from hub.db.session import Database

_ALLOWED_PRIOR_STATUS = {
    SkillStatus.LISTED: SkillStatus.PENDING_REVIEW,
    SkillStatus.REJECTED: SkillStatus.PENDING_REVIEW,
    SkillStatus.UNLISTED: SkillStatus.LISTED,
}


def _required(value: str, field_name: str) -> str:
    clean_value = value.strip()
    if not clean_value:
        raise ValueError(f"{field_name} must not be empty")
    return clean_value


def _digest(value: str, field_name: str) -> str:
    clean_value = _required(value, field_name)
    prefix, separator, hexadecimal = clean_value.partition(":")
    if (
        prefix != "sha256"
        or separator != ":"
        or len(hexadecimal) != 64
        or any(character not in "0123456789abcdef" for character in hexadecimal)
    ):
        raise ValueError(f"{field_name} must be a lowercase sha256 digest")
    return clean_value


def _conflict(operation: str, exc: IntegrityError) -> PersistenceConflictError:
    return PersistenceConflictError(
        f"{operation} conflicts with an existing durable record"
    )


class HubRepository:
    """Persistence boundary for atomic Hub database operations.

    Actor identifiers accepted here must come from server-authenticated context,
    never request bodies or unsigned skill metadata. Audit timestamps are omitted
    from the API entirely and generated by the database.
    """

    def __init__(self, database: Database) -> None:
        self._database = database

    async def create_author(
        self,
        *,
        external_subject: str,
        display_handle: str,
        public_key_b64: str,
    ) -> AuthorModel:
        author = AuthorModel(
            external_subject=_required(external_subject, "external_subject"),
            display_handle=_required(display_handle, "display_handle"),
            public_key_b64=_required(public_key_b64, "public_key_b64"),
        )
        try:
            async with self._database.transaction() as session:
                session.add(author)
                await session.flush()
        except IntegrityError as exc:
            raise _conflict("author creation", exc) from exc
        return author

    async def add_credential(
        self,
        *,
        author_id: str,
        kind: str,
        lookup_id: str,
        credential_hash: str,
        expires_at: datetime | None = None,
    ) -> AuthorCredentialModel:
        credential = AuthorCredentialModel(
            author_id=_required(author_id, "author_id"),
            kind=_required(kind, "kind"),
            lookup_id=_required(lookup_id, "lookup_id"),
            credential_hash=_digest(credential_hash, "credential_hash"),
            expires_at=expires_at,
        )
        try:
            async with self._database.transaction() as session:
                session.add(credential)
                await session.flush()
        except IntegrityError as exc:
            raise _conflict("credential creation", exc) from exc
        return credential

    async def create_publication(
        self,
        *,
        name: str,
        version: str,
        author_id: str,
        artifact_digest: str,
        manifest_digest: str,
        storage_key: str,
        byte_size: int,
        artifact_signature: str,
        manifest_signature: str,
        declares_tier_cd: bool,
        initial_status: SkillStatus,
        authenticated_actor_id: str,
        reason: str,
        correlation_id: str,
        idempotency_key: str,
    ) -> SkillVersionModel:
        if initial_status not in {
            SkillStatus.PENDING_REVIEW,
            SkillStatus.LISTED,
        }:
            raise InvalidStateTransitionError(
                "a publication must start as pending_review or listed"
            )
        if declares_tier_cd and initial_status is SkillStatus.LISTED:
            raise InvalidStateTransitionError(
                "Tier C/D skills must enter pending review before listing"
            )
        if byte_size < 0:
            raise ValueError("byte_size must not be negative")

        actor_id = _required(authenticated_actor_id, "authenticated_actor_id")
        clean_artifact_digest = _digest(artifact_digest, "artifact_digest")
        clean_manifest_digest = _digest(manifest_digest, "manifest_digest")
        artifact = ArtifactModel(
            id=new_record_id(),
            artifact_digest=clean_artifact_digest,
            manifest_digest=clean_manifest_digest,
            storage_key=_required(storage_key, "storage_key"),
            byte_size=byte_size,
            artifact_signature=_required(artifact_signature, "artifact_signature"),
            manifest_signature=_required(manifest_signature, "manifest_signature"),
        )
        skill = SkillVersionModel(
            id=new_record_id(),
            name=_required(name, "name"),
            version=_required(version, "version"),
            author_id=_required(author_id, "author_id"),
            artifact_id=artifact.id,
            status=initial_status.value,
            declares_tier_cd=declares_tier_cd,
        )
        audit = SkillTransitionAuditModel(
            id=new_record_id(),
            skill_version_id=skill.id,
            transition_number=1,
            actor_id=actor_id,
            prior_status=None,
            new_status=initial_status.value,
            reason=_required(reason, "reason"),
            correlation_id=_required(correlation_id, "correlation_id"),
            idempotency_key=_required(idempotency_key, "idempotency_key"),
            artifact_digest=clean_artifact_digest,
            manifest_digest=clean_manifest_digest,
        )

        try:
            async with self._database.transaction() as session:
                session.add(artifact)
                await session.flush()
                session.add(skill)
                await session.flush()
                session.add(audit)
                await session.flush()
        except IntegrityError as exc:
            raise _conflict("skill publication", exc) from exc
        return skill

    async def transition_skill(
        self,
        *,
        name: str,
        version: str,
        target_status: SkillStatus,
        authenticated_actor_id: str,
        reason: str,
        correlation_id: str,
        idempotency_key: str,
    ) -> SkillVersionModel:
        prior_status = _ALLOWED_PRIOR_STATUS.get(target_status)
        if prior_status is None:
            raise InvalidStateTransitionError(
                f"skills cannot transition to {target_status.value}"
            )

        actor_id = _required(authenticated_actor_id, "authenticated_actor_id")
        values: dict[str, object] = {
            "status": target_status.value,
            "revision": SkillVersionModel.revision + 1,
            "updated_at": func.current_timestamp(),
        }
        if target_status is SkillStatus.LISTED:
            values.update(
                review_approved_at=func.current_timestamp(),
                review_approved_by=actor_id,
            )

        statement = (
            update(SkillVersionModel)
            .where(
                SkillVersionModel.name == _required(name, "name"),
                SkillVersionModel.version == _required(version, "version"),
                SkillVersionModel.status == prior_status.value,
            )
            .values(**values)
            .returning(SkillVersionModel)
        )

        try:
            async with self._database.transaction() as session:
                result = await session.execute(statement)
                skill = result.scalar_one_or_none()
                if skill is None:
                    await self._raise_transition_failure(
                        session=session,
                        name=name,
                        version=version,
                        target_status=target_status,
                    )

                artifact = await session.get(ArtifactModel, skill.artifact_id)
                if artifact is None:
                    raise RecordNotFoundError(
                        "the skill publication has no durable artifact"
                    )
                session.add(
                    SkillTransitionAuditModel(
                        id=new_record_id(),
                        skill_version_id=skill.id,
                        transition_number=skill.revision,
                        actor_id=actor_id,
                        prior_status=prior_status.value,
                        new_status=target_status.value,
                        reason=_required(reason, "reason"),
                        correlation_id=_required(correlation_id, "correlation_id"),
                        idempotency_key=_required(idempotency_key, "idempotency_key"),
                        artifact_digest=artifact.artifact_digest,
                        manifest_digest=artifact.manifest_digest,
                    )
                )
                await session.flush()
        except IntegrityError as exc:
            raise _conflict("skill transition", exc) from exc
        return skill

    async def increment_downloads(self, *, name: str, version: str) -> int:
        statement = (
            update(SkillVersionModel)
            .where(
                SkillVersionModel.name == _required(name, "name"),
                SkillVersionModel.version == _required(version, "version"),
                SkillVersionModel.status == SkillStatus.LISTED.value,
            )
            .values(downloads=SkillVersionModel.downloads + 1)
            .returning(SkillVersionModel.downloads)
        )
        async with self._database.transaction() as session:
            result = await session.execute(statement)
            downloads = result.scalar_one_or_none()
            if downloads is None:
                skill = await self._get_skill_in_session(
                    session=session, name=name, version=version
                )
                raise InvalidStateTransitionError(
                    f"{skill.status} skills cannot be downloaded"
                )
        return downloads

    async def get_skill(self, *, name: str, version: str) -> SkillVersionModel:
        async with self._database.transaction() as session:
            return await self._get_skill_in_session(
                session=session, name=name, version=version
            )

    async def get_transition_history(
        self, *, name: str, version: str
    ) -> list[SkillTransitionAuditModel]:
        async with self._database.transaction() as session:
            skill = await self._get_skill_in_session(
                session=session, name=name, version=version
            )
            result = await session.scalars(
                select(SkillTransitionAuditModel)
                .where(SkillTransitionAuditModel.skill_version_id == skill.id)
                .order_by(SkillTransitionAuditModel.transition_number)
            )
            return list(result)

    async def _get_skill_in_session(
        self, *, session: AsyncSession, name: str, version: str
    ) -> SkillVersionModel:
        result = await session.scalars(
            select(SkillVersionModel).where(
                SkillVersionModel.name == _required(name, "name"),
                SkillVersionModel.version == _required(version, "version"),
            )
        )
        skill = result.one_or_none()
        if skill is None:
            raise RecordNotFoundError(f"skill {name}@{version} was not found")
        return skill

    async def _raise_transition_failure(
        self,
        *,
        session: AsyncSession,
        name: str,
        version: str,
        target_status: SkillStatus,
    ) -> NoReturn:
        skill = await self._get_skill_in_session(
            session=session, name=name, version=version
        )
        raise InvalidStateTransitionError(
            f"skill status cannot transition from {skill.status} "
            f"to {target_status.value}"
        )
