# Copyright 2026 Ori Nexus Systems LTD
# SPDX-License-Identifier: Apache-2.0

"""Transactional persistence operations for authors and skill publications."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from typing import NoReturn

from sqlalchemy import Select, insert, literal, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from hub.core.models import ScannerVerdict, SkillStatus
from hub.db._models import (
    ArtifactModel,
    AuthorModel,
    SkillTransitionAuditModel,
    SkillVersionModel,
    new_record_id,
)
from hub.db.errors import (
    InvalidStateTransitionError,
    PersistenceConflictError,
    RecordNotFoundError,
)
from hub.db.session import Database

_ALLOWED_PRIOR_STATUS = {
    SkillStatus.LISTED: SkillStatus.PENDING_REVIEW,
    SkillStatus.REJECTED: SkillStatus.PENDING_REVIEW,
    SkillStatus.UNLISTED: SkillStatus.LISTED,
}


@dataclass(frozen=True)
class PublicSkillVersion:
    """Public, listed-only publication data for Hub read endpoints."""

    name: str
    version: str
    author: str
    downloads: int
    created_at: datetime
    artifact_digest: str
    byte_size: int


def _required(value: str, field_name: str) -> str:
    clean_value = value.strip()
    if not clean_value:
        raise ValueError(f"{field_name} must not be empty")
    return clean_value


def _digest(value: str, field_name: str) -> str:
    clean_value = _required(value, field_name)
    prefix, separator, hexadecimal = clean_value.partition(":")
    if (
        prefix != "sha256"
        or separator != ":"
        or len(hexadecimal) != 64
        or any(character not in "0123456789abcdef" for character in hexadecimal)
    ):
        raise ValueError(f"{field_name} must be a lowercase sha256 digest")
    return clean_value


def _conflict(operation: str, exc: IntegrityError) -> PersistenceConflictError:
    return PersistenceConflictError(
        f"{operation} conflicts with an existing durable record"
    )


class HubRepository:
    """Persistence boundary for atomic Hub database operations.

    Actor identifiers accepted here must come from server-authenticated context,
    never request bodies or unsigned skill metadata. Audit timestamps are omitted
    from the API entirely and generated by the database.
    """

    def __init__(self, database: Database) -> None:
        self._database = database

    async def create_publication(
        self,
        *,
        name: str,
        version: str,
        artifact_digest: str,
        manifest_digest: str,
        storage_key: str,
        byte_size: int,
        artifact_signature: str,
        manifest_signature: str,
        scanner_verdict: ScannerVerdict,
        scanner_detail: str,
        author_artifact_digest: str,
        author_artifact_signature: str,
        declares_tier_cd: bool,
        initial_status: SkillStatus,
        authenticated_actor_id: str,
        reason: str,
        correlation_id: str,
        idempotency_key: str,
    ) -> SkillVersionModel:
        if initial_status not in {
            SkillStatus.PENDING_REVIEW,
            SkillStatus.LISTED,
        }:
            raise InvalidStateTransitionError(
                "a publication must start as pending_review or listed"
            )
        if declares_tier_cd and initial_status is SkillStatus.LISTED:
            raise InvalidStateTransitionError(
                "Tier C/D skills must enter pending review before listing"
            )
        if byte_size < 0:
            raise ValueError("byte_size must not be negative")
        if len(scanner_detail) > 1024:
            raise ValueError("scanner_detail must not exceed 1024 characters")

        actor_id = _required(authenticated_actor_id, "authenticated_actor_id")
        clean_artifact_digest = _digest(artifact_digest, "artifact_digest")
        clean_manifest_digest = _digest(manifest_digest, "manifest_digest")
        artifact = ArtifactModel(
            id=new_record_id(),
            artifact_digest=clean_artifact_digest,
            manifest_digest=clean_manifest_digest,
            storage_key=_required(storage_key, "storage_key"),
            byte_size=byte_size,
            artifact_signature=_required(artifact_signature, "artifact_signature"),
            manifest_signature=_required(manifest_signature, "manifest_signature"),
            scanner_verdict=scanner_verdict.value,
            scanner_detail=scanner_detail,
            author_artifact_digest=_digest(
                author_artifact_digest, "author_artifact_digest"
            ),
            author_artifact_signature=_required(
                author_artifact_signature, "author_artifact_signature"
            ),
        )
        skill = SkillVersionModel(
            id=new_record_id(),
            name=_required(name, "name"),
            version=_required(version, "version"),
            author_id=actor_id,
            artifact_id=artifact.id,
            status=initial_status.value,
            declares_tier_cd=declares_tier_cd,
        )
        audit = SkillTransitionAuditModel(
            id=new_record_id(),
            skill_version_id=skill.id,
            transition_number=1,
            actor_id=actor_id,
            prior_status=None,
            new_status=initial_status.value,
            reason=_required(reason, "reason"),
            correlation_id=_required(correlation_id, "correlation_id"),
            idempotency_key=_required(idempotency_key, "idempotency_key"),
            artifact_digest=clean_artifact_digest,
            manifest_digest=clean_manifest_digest,
        )

        try:
            async with self._database.transaction() as session:
                session.add(artifact)
                await session.flush()
                session.add(audit)
                await session.flush()
                session.add(skill)
                await session.flush()
        except IntegrityError as exc:
            raise _conflict("skill publication", exc) from exc
        return skill

    async def transition_skill(
        self,
        *,
        name: str,
        version: str,
        target_status: SkillStatus,
        authenticated_actor_id: str,
        reason: str,
        correlation_id: str,
        idempotency_key: str,
    ) -> SkillVersionModel:
        prior_status = _ALLOWED_PRIOR_STATUS.get(target_status)
        if prior_status is None:
            raise InvalidStateTransitionError(
                f"skills cannot transition to {target_status.value}"
            )

        clean_name = _required(name, "name")
        clean_version = _required(version, "version")
        actor_id = _required(authenticated_actor_id, "authenticated_actor_id")
        clean_reason = _required(reason, "reason")
        clean_correlation_id = _required(correlation_id, "correlation_id")
        clean_idempotency_key = _required(idempotency_key, "idempotency_key")
        audit_id = new_record_id()
        transition = (
            select(
                literal(audit_id),
                SkillVersionModel.id,
                SkillVersionModel.revision + 1,
                literal(actor_id),
                literal(prior_status.value),
                literal(target_status.value),
                literal(clean_reason),
                literal(clean_correlation_id),
                literal(clean_idempotency_key),
                ArtifactModel.artifact_digest,
                ArtifactModel.manifest_digest,
            )
            .join(
                ArtifactModel,
                ArtifactModel.id == SkillVersionModel.artifact_id,
            )
            .where(
                SkillVersionModel.name == clean_name,
                SkillVersionModel.version == clean_version,
                SkillVersionModel.status == prior_status.value,
            )
        )
        statement = (
            insert(SkillTransitionAuditModel)
            .from_select(
                [
                    "id",
                    "skill_version_id",
                    "transition_number",
                    "actor_id",
                    "prior_status",
                    "new_status",
                    "reason",
                    "correlation_id",
                    "idempotency_key",
                    "artifact_digest",
                    "manifest_digest",
                ],
                transition,
            )
            .returning(SkillTransitionAuditModel.skill_version_id)
        )

        try:
            async with self._database.transaction() as session:
                result = await session.execute(statement)
                skill_id = result.scalar_one_or_none()
                if skill_id is None:
                    await self._raise_transition_failure(
                        session=session,
                        name=clean_name,
                        version=clean_version,
                        target_status=target_status,
                    )

                skill = await session.get(SkillVersionModel, skill_id)
                if skill is None:
                    raise RecordNotFoundError(
                        "the transitioned skill publication was not found"
                    )
        except IntegrityError as exc:
            raise _conflict("skill transition", exc) from exc
        return skill

    async def increment_downloads(self, *, name: str, version: str) -> int:
        statement = (
            update(SkillVersionModel)
            .where(
                SkillVersionModel.name == _required(name, "name"),
                SkillVersionModel.version == _required(version, "version"),
                SkillVersionModel.status == SkillStatus.LISTED.value,
            )
            .values(downloads=SkillVersionModel.downloads + 1)
            .returning(SkillVersionModel.downloads)
        )
        async with self._database.transaction() as session:
            result = await session.execute(statement)
            downloads = result.scalar_one_or_none()
            if downloads is None:
                skill = await self._get_skill_in_session(
                    session=session, name=name, version=version
                )
                raise InvalidStateTransitionError(
                    f"{skill.status} skills cannot be downloaded"
                )
        return downloads

    async def get_skill(self, *, name: str, version: str) -> SkillVersionModel:
        async with self._database.transaction() as session:
            return await self._get_skill_in_session(
                session=session, name=name, version=version
            )

    async def list_listed_skills(self, *, limit: int) -> list[PublicSkillVersion]:
        if not 1 <= limit <= 100:
            raise ValueError("limit must be between 1 and 100")
        async with self._database.transaction() as session:
            result = await session.execute(
                self._listed_skill_statement()
                .order_by(SkillVersionModel.name, SkillVersionModel.version.desc())
                .limit(limit)
            )
            return self._public_skill_versions(result.tuples().all())

    async def list_listed_versions(self, *, name: str) -> list[PublicSkillVersion]:
        clean_name = _required(name, "name")
        async with self._database.transaction() as session:
            result = await session.execute(
                self._listed_skill_statement()
                .where(SkillVersionModel.name == clean_name)
                .order_by(SkillVersionModel.version.desc())
            )
            return self._public_skill_versions(result.tuples().all())

    async def get_listed_skill(self, *, name: str, version: str) -> PublicSkillVersion:
        clean_name = _required(name, "name")
        clean_version = _required(version, "version")
        async with self._database.transaction() as session:
            result = await session.execute(
                self._listed_skill_statement().where(
                    SkillVersionModel.name == clean_name,
                    SkillVersionModel.version == clean_version,
                )
            )
            records = self._public_skill_versions(result.tuples().all())
        if not records:
            raise RecordNotFoundError(f"listed skill {name}@{version} was not found")
        return records[0]

    async def publication_recorded_for_idempotency_key(
        self, *, actor_id: str, idempotency_key: str
    ) -> bool:
        """Return whether the actor already consumed this idempotency key."""

        actor = _required(actor_id, "actor_id")
        key = _required(idempotency_key, "idempotency_key")
        async with self._database.transaction() as session:
            result = await session.scalars(
                select(SkillTransitionAuditModel.id)
                .where(
                    SkillTransitionAuditModel.actor_id == actor,
                    SkillTransitionAuditModel.idempotency_key == key,
                )
                .limit(1)
            )
            return result.first() is not None

    async def skill_version_exists(self, *, name: str, version: str) -> bool:
        """Return whether any publication already holds this skill identity."""

        clean_name = _required(name, "name")
        clean_version = _required(version, "version")
        async with self._database.transaction() as session:
            result = await session.scalars(
                select(SkillVersionModel.id)
                .where(
                    SkillVersionModel.name == clean_name,
                    SkillVersionModel.version == clean_version,
                )
                .limit(1)
            )
            return result.first() is not None

    async def get_transition_history(
        self, *, name: str, version: str
    ) -> list[SkillTransitionAuditModel]:
        async with self._database.transaction() as session:
            skill = await self._get_skill_in_session(
                session=session, name=name, version=version
            )
            result = await session.scalars(
                select(SkillTransitionAuditModel)
                .where(SkillTransitionAuditModel.skill_version_id == skill.id)
                .order_by(SkillTransitionAuditModel.transition_number)
            )
            return list(result)

    async def _get_skill_in_session(
        self, *, session: AsyncSession, name: str, version: str
    ) -> SkillVersionModel:
        result = await session.scalars(
            select(SkillVersionModel).where(
                SkillVersionModel.name == _required(name, "name"),
                SkillVersionModel.version == _required(version, "version"),
            )
        )
        skill = result.one_or_none()
        if skill is None:
            raise RecordNotFoundError(f"skill {name}@{version} was not found")
        return skill

    @staticmethod
    def _listed_skill_statement() -> Select[
        tuple[SkillVersionModel, AuthorModel, ArtifactModel]
    ]:
        return (
            select(SkillVersionModel, AuthorModel, ArtifactModel)
            .join(AuthorModel, AuthorModel.id == SkillVersionModel.author_id)
            .join(ArtifactModel, ArtifactModel.id == SkillVersionModel.artifact_id)
            .where(SkillVersionModel.status == SkillStatus.LISTED.value)
        )

    @staticmethod
    def _public_skill_versions(
        rows: Sequence[tuple[SkillVersionModel, AuthorModel, ArtifactModel]],
    ) -> list[PublicSkillVersion]:
        records: list[PublicSkillVersion] = []
        for skill, author, artifact in rows:
            records.append(
                PublicSkillVersion(
                    name=skill.name,
                    version=skill.version,
                    author=author.display_handle,
                    downloads=skill.downloads,
                    created_at=skill.created_at,
                    artifact_digest=artifact.artifact_digest,
                    byte_size=artifact.byte_size,
                )
            )
        return records

    async def _raise_transition_failure(
        self,
        *,
        session: AsyncSession,
        name: str,
        version: str,
        target_status: SkillStatus,
    ) -> NoReturn:
        skill = await self._get_skill_in_session(
            session=session, name=name, version=version
        )
        raise InvalidStateTransitionError(
            f"skill status cannot transition from {skill.status} "
            f"to {target_status.value}"
        )
